source 'http://rubygems.org'

gem 'sinatra'
gem 'require_all'
gem 'activerecord', '6.1.7.1'
gem 'sinatra-activerecord'
gem 'rake'

group :development do
  gem 'shotgun'
  gem 'pry'
  gem 'sqlite3', '~> 1.3.6'
end